image:
  file: .gitpod.Dockerfile
tasks:
  - init: npm install
    command: cd services/website && npm run dev
  - command: |
      gp ports await 3000
      npm run generate
ports:
  - port: 3000
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 10000
    onOpen: ignore

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
